### ISSUE TITLE
Getting Started / Examples

### ISSUE THREAD

**Issue by petesisk** [euracresearch/go-snipeit#13]
Hi folks.

Could you provide some examples or a getting started guide for folks that would like to use this library with their own Kandji tenant?

Thanks!

**Comment by petesisk** [comment]
Yes, I meant Snipe-IT, and I obviously need to proof-read my issues ;)



Thanks for the snippet ; I'm seeing an error with the Limit option:
`unknown field Limit in struct literal`

If I remove the Limit line, VSCode offers to `fill snipeit.LocationOptions`
If I do this it fills it with :
```
opts := &snipeit.LocationOptions{
	Search: "",
}
```
If I switch to HardwareOptions and fill, I get the following : 
```
opts := &snipeit.HardwareOptions{
	LocationID: 0,
	CompanyID:  0,
}
```

Adding `Limit: 10` to this again returns the `unknown field Limit in struct literal` error.

If possible, could you show a working example using the publicly accessible develop.snipeitapp.com API to query Hardware?
https://snipe-it.readme.io/reference/hardware-list

Appreciate the help!

**Comment by palmamartin** [comment]
The error you get is because you probably don't use the latest version/commit of the library. We tagged an early version with  `v0.0.1` by mistake and if you simply do a `go get github.com/euracresearch/go-snipeit@latest` it will use the `v0.0.1` tagged version. You can check the version of the library looking at your `go.mod` file.

In order to get the latest version/commit you can do the following: 

```
$ go get github.com/euracresearch/go-snipeit@master
```

or if you already have a `go.mod` file you can update the library with:

```
$ go get -u  github.com/euracresearch/go-snipeit@master
```

We updated also the README to clarify these things and added and example, using the Hardware endpoint.

**Comment by petesisk** [comment]
Thank you!
